name: build

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - master

jobs:
  build-cross-platform:
    name: test ${{matrix.os}} - ${{matrix.python-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest
        ]
        python-version: [
          '3.6',
          '3.7',
          '3.8',
          '3.9',
          '3.10'
        ]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install mamba
      run: |
        conda install -c conda-forge mamba
    - name: Install dependencies
      run: |
        mamba env update --file environment-test.yml --name base
    - name: Install current project in dev mode
      run: |
        python -m pip install -e .
    - name: Run test suite
      run: python -m pytest -p no:faulthandler --color=yes

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install mamba
        run: |
          conda install -c conda-forge mamba
      - name: Install dependencies
        run: |
          mamba env update --file environment-test.yml --name base
      - name: Install current project in dev mode
        run: |
          pip install -e .
      - name: Install pytest
        run: |
          mamba install -c conda-forge pytest-cov
      - name: Generate Report
        run: |
          python -m pytest --cov-report=xml --cov=.
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        